FROM openjdk:8-jdk-alpine
VOLUME /tmp
ARG JAVA_OPTS
ENV JAVA_OPTS=$JAVA_OPTS
ADD dockerfilesamples.jar dockerfilesamples.jar
EXPOSE 80
ENTRYPOINT exec java $JAVA_OPTS -jar dockerfilesamples.jar
# For Spring-Boot project, use the entrypoint below to reduce Tomcat startup time.
#ENTRYPOINT exec java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar dockerfilesamples.jar
