name: Lint Dockerfiles

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hadolint:
    name: Hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint all Dockerfiles
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "*/Dockerfile"
          recursive: true
